import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#446977",
  },
  header: {
    backgroundColor: "#446977",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 14,
  },
  backButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "rgba(255, 255, 255, 0.18)",
    justifyContent: "center",
    alignItems: "center",
  },
  backButtonText: {
    color: "#fff",
    fontSize: 24,
    fontWeight: "700",
  },
  headerTitle: {
    flex: 1,
    color: "#fff",
    fontSize: 20,
    fontWeight: "800",
    textAlign: "center",
  },
  headerSpacer: {
    width: 44,
  },
  filterContainer: {
    padding: 16,
    backgroundColor: "#7aa7b8",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.08,
    shadowRadius: 14,
    elevation: 6,
  },
  filterScroll: {
    flexGrow: 0,
  },
  filterScrollContent: {
    flexDirection: "row",
    alignItems: "center",
    paddingBottom: 4,
  },
  filterChip: {
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 16,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.3)",
    marginRight: 8,
  },
  filterChipActive: {
    backgroundColor: "#1ca8b2",
    borderColor: "#1ca8b2",
  },
  filterChipText: {
    color: "#d4e2ea",
    fontSize: 13,
    fontWeight: "600",
  },
  filterChipTextActive: {
    color: "#ffffff",
  },
  content: {
    flex: 1,
    backgroundColor: "#446977",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    overflow: "hidden",
  },
  list: {
    paddingTop: 24,
    paddingHorizontal: 20,
    paddingBottom: 30,
  },
  card: {
    backgroundColor: "#7aa7b8",
    borderRadius: 18,
    padding: 18,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: "#ffffff",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.08,
    shadowRadius: 16,
    elevation: 5,
  },
  cardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  cardTitle: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "800",
    flex: 1,
    marginRight: 10,
  },
  cardSubtitle: {
    color: "#ffffff",
    fontSize: 15,
    fontWeight: "700",
    marginBottom: 6,
  },
  cardDate: {
    color: "#bec5d5",
    fontSize: 12,
  },
  cardAmount: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "800",
    marginTop: 8,
  },
  centered: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 40,
  },
  loadingText: {
    marginTop: 10,
    color: "#ffffff",
    fontSize: 16,
  },
  errorText: {
    color: "#dc3545",
    marginBottom: 20,
    fontSize: 16,
    textAlign: "center",
  },
  retryButton: {
    backgroundColor: "#1ca8b2",
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 12,
  },
  retryText: {
    color: "#ffffff",
    fontWeight: "700",
  },
  emptyText: {
    color: "#ffffff",
    fontSize: 18,
    fontWeight: "700",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContent: {
    backgroundColor: "#7aa7b8",
    borderRadius: 18,
    padding: 20,
    borderWidth: 1,
    borderColor: "#ffffff",
    width: "88%",
    maxHeight: "80%",
  },
  modalTitle: {
    color: "#ffffff",
    fontSize: 18,
    fontWeight: "800",
    marginBottom: 15,
    textAlign: "center",
  },
  detailRow: {
    marginBottom: 12,
  },
  detailLabel: {
    color: "#bec5d5",
    fontSize: 13,
  },
  detailValue: {
    color: "#ffffff",
    fontSize: 15,
    fontWeight: "700",
    marginTop: 2,
  },
  closeButton: {
    marginTop: 15,
    backgroundColor: "#1ca8b2",
    padding: 12,
    borderRadius: 12,
    alignItems: "center",
  },
  closeButtonText: {
    color: "#ffffff",
    fontWeight: "700",
  },
});
