import { StyleSheet } from "react-native";

export default StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: "#446977" },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#446977",
    paddingHorizontal: 20,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: "#7aa7b8",
  },
  headerLeft: { flexDirection: "row", alignItems: "center", gap: 10 },
  headerIconBox: {
    width: 60,
    height: 60,
    borderRadius: 12,
    backgroundColor: "#446977",
    alignItems: "center",
    justifyContent: "center",
  },
  logoImage: {
    width: 200,
    height: 100,
    resizeMode: "contain",
    marginLeft: 115,
  },
  headerRight: { flexDirection: "row", alignItems: "center", gap: 10 },
  headerUserInfo: {
    alignItems: "flex-end",
    backgroundColor: "rgba(255,255,255,0.12)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.35)",
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 9,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.12,
    shadowRadius: 10,
    elevation: 4,
  },
  headerUserName: { color: "#ffffff", fontSize: 16, fontWeight: "800" },
  headerUserRole: { color: "#d8e3ea", fontSize: 12, marginTop: 2 },
  scrollView: { flex: 1, backgroundColor: "#446977" },
  scrollContent: { padding: 20, paddingBottom: 40 },
  welcomeSection: { marginBottom: 24, marginTop: 8 },
  welcomeTitle: {
    color: "#ffffff",
    fontSize: 24,
    fontWeight: "700",
    letterSpacing: 0.2,
  },
  welcomeSubtitle: { color: "#ffffff", fontSize: 14, marginTop: 4 },
  cardsRow: { flexDirection: "row", gap: 12, marginBottom: 24 },
  actionCard: {
    flex: 1,
    backgroundColor: "#7aa7b8",
    borderRadius: 18,
    padding: 14,
    borderWidth: 1,
    borderColor: "#ffffff",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.1,
    shadowRadius: 16,
    elevation: 5,
  },
  actionIconBox: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: "#1ca8b2",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 10,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.55)",
  },
  actionIcon: {
    width: 28,
    height: 28,
    resizeMode: "contain",
    tintColor: "#ffffff",
  },
  actionTitle: {
    color: "#ffffff",
    fontSize: 15,
    fontWeight: "700",
    marginBottom: 6,
  },
  actionSubtitle: { color: "#ffffff", fontSize: 13, lineHeight: 18 },
  quickOverview: {
    backgroundColor: "#7aa7b8",
    borderRadius: 18,
    padding: 18,
    borderWidth: 1,
    borderColor: "#ffffff",
    marginBottom: 24,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.08,
    shadowRadius: 16,
    elevation: 5,
  },
  quickOverviewLabel: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "700",
    letterSpacing: 1.2,
    marginBottom: 16,
  },
  statsRow: { flexDirection: "row", alignItems: "center" },
  statBox: { flex: 1, alignItems: "center" },
  statLabel: {
    color: "#ffffff",
    fontSize: 14,
    textAlign: "center",
    marginBottom: 6,
  },
  statValue: { color: "#ffffff", fontSize: 34, fontWeight: "700" },
  statDivider: { width: 1, height: 40, backgroundColor: "#ffffff" },
  recentSection: {
    backgroundColor: "#7aa7b8",
    borderRadius: 18,
    padding: 18,
    borderWidth: 1,
    borderColor: "#ffffff",
    marginBottom: 24,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.08,
    shadowRadius: 16,
    elevation: 5,
  },
  recentHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  recentHeaderLink: {
    color: "#d8e3ea",
    fontSize: 13,
    fontWeight: "700",
  },
  recentSectionLabel: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "700",
    letterSpacing: 1.2,
  },
  recentEmptyText: {
    color: "#ffffff",
    fontSize: 14,
    lineHeight: 20,
  },
  recentItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 12,
    paddingHorizontal: 10,
    borderRadius: 12,
    backgroundColor: "rgba(255,255,255,0.08)",
    marginBottom: 12,
  },
  recentItemRow: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
  },
  recentStatusDot: {
    width: 10,
    height: 10,
    borderRadius: 10,
    backgroundColor: "#fbbf24",
    marginRight: 12,
  },
  recentItemLeft: { flex: 1, paddingRight: 12 },
  recentItemType: {
    color: "#ffffff",
    fontSize: 15,
    fontWeight: "700",
    marginBottom: 4,
  },
  recentItemSubtitle: {
    color: "#d8e3ea",
    fontSize: 12,
  },
  recentItemStatus: {
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.16)",
  },
  recentItemStatusText: {
    color: "#ffffff",
    fontSize: 12,
    fontWeight: "700",
  },
  logoutButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#ffffff",
    borderRadius: 14,
    paddingVertical: 16,
    gap: 8,
    backgroundColor: "rgba(224,90,90,0.14)",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.12,
    shadowRadius: 10,
    elevation: 4,
  },
  logoutIcon: { color: "#e05a5a", fontSize: 16, fontWeight: "700" },
  logoutText: { color: "#e05a5a", fontSize: 15, fontWeight: "600" },
});
