import { StyleSheet } from 'react-native';

export const COLORS = {
  primary:    '#2ab8c4',
  background: '#1a3a3f',
  cardBg:     '#1e5c6b',
  white:      '#f0f4f6',
  error:      '#e05a5a',
  muted:      'rgba(255,255,255,0.6)',
  success:    '#3dba7a',
  warning:    '#2ab8c4',
  cancelled:  '#e05a5a',
};

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.background },
  topbar: {
    backgroundColor: COLORS.background,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: 50,
    paddingBottom: 14,
  },
  topbarTitle: {
    flex: 1,
    fontSize: 18,
    fontWeight: '800',
    color: COLORS.white,
    textAlign: 'center',
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  headerIconButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: COLORS.primary,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.55)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.18,
    shadowRadius: 8,
    elevation: 5,
  },
  headerIconText: {
    color: COLORS.white,
    fontSize: 18,
    fontWeight: '800',
  },
  searchInput: {
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.15)',
    paddingVertical: 12,
    paddingHorizontal: 16,
    marginHorizontal: 16,
    marginBottom: 18,
    borderRadius: 14,
    color: COLORS.white,
    backgroundColor: COLORS.cardBg,
    fontSize: 14,
  },
  card: {
    backgroundColor: COLORS.cardBg,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.10)',
    borderRadius: 18,
    padding: 18,
    marginHorizontal: 20,
    marginBottom: 14,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.08,
    shadowRadius: 16,
    elevation: 5,
  },
  row: {
    flexDirection: 'row', alignItems: 'center',
    padding: 12, borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.08)', gap: 10,
  },
  partName:  { fontSize: 14, fontWeight: 'bold', color: COLORS.white, marginBottom: 2 },
  partStock: { fontSize: 12, color: COLORS.muted },
  partPrice: { fontSize: 13, fontWeight: 'bold', color: COLORS.white },
  addButton: {
    width: 28, height: 28, borderRadius: 14,
    backgroundColor: COLORS.primary,
    justifyContent: 'center', alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.3)',
  },
  addButtonDisabled: { backgroundColor: 'rgba(255,255,255,0.12)' },
  addButtonText: { color: COLORS.white, fontSize: 18, lineHeight: 18, textAlign: 'center', includeFontPadding: false },
  button: {
    backgroundColor: COLORS.primary, padding: 15,
    borderRadius: 12, alignItems: 'center',
    marginTop: 15, width: '70%', alignSelf: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.25)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.2,
    shadowRadius: 9,
    elevation: 6,
  },
  buttonDisabled: { backgroundColor: 'rgba(255,255,255,0.12)' },
  buttonText: { color: COLORS.white, fontWeight: 'bold', fontSize: 16 },
  checkoutButton: {
    width: '86%',
    marginTop: 18,
    marginBottom: 24,
  },
  backButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(255,255,255,0.10)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.20)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  backButtonText: {
    color: COLORS.white,
    fontSize: 24,
    fontWeight: '700',
  },
  cartButton: {
    height: 36,
    borderRadius: 18,
    backgroundColor: COLORS.primary,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.25)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 14,
  },
  cartButtonText: {
    color: COLORS.white,
    fontSize: 13,
    fontWeight: '800',
  },
  label:     { fontSize: 11, color: COLORS.muted, textTransform: 'uppercase', letterSpacing: 0.5, marginBottom: 4 },
  emptyText: { textAlign: 'center', color: COLORS.muted, marginTop: 60, fontSize: 14 },
  separator: { height: 1, backgroundColor: 'rgba(255,255,255,0.08)', marginHorizontal: 12 },
  qtyBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.20)',
    backgroundColor: 'rgba(255,255,255,0.08)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  qtyBtnDisabled: { opacity: 0.4 },
  qtyBtnText: { color: COLORS.white, fontSize: 18, fontWeight: '800' },
  qtyControls: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  qtyNum: { fontSize: 15, fontWeight: 'bold', color: COLORS.white, minWidth: 20, textAlign: 'center' },
  totalRow: {
    flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center',
    paddingHorizontal: 20, paddingTop: 16,
  },
  cartFooter: {
    borderTopWidth: 1,
    borderTopColor: 'rgba(255,255,255,0.12)',
    paddingBottom: 10,
  },
  totalLabel: { fontSize: 14, color: COLORS.muted },
  totalVal:   { fontSize: 18, fontWeight: 'bold', color: COLORS.white },
  emptyCartContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 12,
  },
  emptyActionText: {
    color: COLORS.primary,
    fontWeight: 'bold',
  },
  pill:     { borderRadius: 8, paddingHorizontal: 8, paddingVertical: 3, overflow: 'hidden' },
  pillText: { fontSize: 11, fontWeight: 'bold', color: COLORS.white },
});
